# Generated by Django 4.2.1 on 2023-08-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.FileField(upload_to='media/images/')),
                ('features', models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1)),
                ('active', models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1)),
            ],
        ),
    ]
