# Generated by Django 4.2.1 on 2023-08-02 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftitle', models.CharField(max_length=50)),
                ('fdesc', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('fimg', models.FileField(upload_to='media/food/')),
                ('features', models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1)),
                ('active', models.CharField(choices=[('Y', 'yes'), ('N', 'no')], max_length=1)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
    ]
