# Generated by Django 4.2.1 on 2023-08-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('totalprice', models.ImageField(upload_to='')),
                ('oder_date', models.DateField()),
                ('status', models.CharField(choices=[('Odered', 'Odered'), ('Deliverd', 'Deliverd'), ('Delivering', 'Delivering'), ('Canceled', 'Canceled')], max_length=20)),
                ('customer_name', models.CharField(max_length=40)),
                ('customer_contact', models.IntegerField(max_length=10)),
                ('customer_email', models.CharField(max_length=25)),
                ('customer_address', models.CharField(max_length=50)),
            ],
        ),
    ]
