# Generated by Django 4.2.1 on 2023-08-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_contact',
            field=models.IntegerField(),
        ),
    ]
