# Generated by Django 4.2.1 on 2023-08-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_customer_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='totalprice',
            field=models.IntegerField(),
        ),
    ]
