# Generated by Django 4.2.1 on 2023-08-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_totalprice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='odeer',
        ),
    ]
